defmodule Ziwoas.RailsFixture do
  @moduledoc """
  Builds SQLite files from what Rails wrote (`priv/rails_schema.sql`, `rails_rows.sql`,
  both generated by the removed Rails app and frozen since). Goes through the raw
  driver, never the Repo, so the read-only Repo can open the result.
  """
  alias Exqlite.Sqlite3

  @schema_sql Path.expand("../../priv/rails_schema.sql", __DIR__)
  @rows_sql Path.expand("rails_rows.sql", __DIR__)
  @external_resource @schema_sql
  @external_resource @rows_sql

  @tmp Path.expand("../../tmp", __DIR__)

  @doc """
  Builds `path` from the Rails schema, plus Rails' sample rows unless `rows: false`.
  It deletes `path` first, so it builds only under `tmp/`: `ZIWOAS_DB=<file>
  mix test` raises here instead of wiping that file.
  """
  def build!(path \\ Application.fetch_env!(:ziwoas, Ziwoas.Repo)[:database], opts \\ []) do
    unless String.starts_with?(
             Ziwoas.ShadowDb.real_path(path),
             Ziwoas.ShadowDb.real_path(@tmp) <> "/"
           ),
           do: raise("RailsFixture builds test databases under #{@tmp} only, not #{path}")

    File.mkdir_p!(Path.dirname(path))
    for suffix <- ["", "-wal", "-shm"], do: File.rm(path <> suffix)

    {:ok, conn} = Sqlite3.open(path)

    try do
      # Rails switches every database it opens to WAL.
      :ok = Sqlite3.execute(conn, "PRAGMA journal_mode = WAL")
      :ok = Sqlite3.execute(conn, File.read!(@schema_sql))
      if Keyword.get(opts, :rows, true), do: :ok = Sqlite3.execute(conn, File.read!(@rows_sql))
    after
      Sqlite3.close(conn)
    end

    path
  end
end
