# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

aggregator_schedule: &aggregator_schedule
  aggregate_energy_samples:
    class: AggregatorJob
    queue: default
    schedule: at 3:15am every day

  fetch_current_weather:
    class: WeatherCurrentJob
    queue: default
    schedule: every 15 minutes

  push_trmnl_widget:
    class: TrmnlPushJob
    queue: default
    schedule: every 15 minutes

  fetch_today_weather:
    class: WeatherTodayJob
    queue: default
    schedule: every hour

  fetch_weather_forecast:
    class: WeatherForecastJob
    queue: default
    schedule: every 3 hours

  fetch_historic_weather:
    class: WeatherHistoricJob
    queue: default
    schedule: at 3:45am every day

development:
  <<: *aggregator_schedule

production:
  <<: *aggregator_schedule

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
